# ワークフローの名前を定義する
name: buildチェックするお

# ワークフローの実行方法を定義する
on:
  pull_request:

# ワークフローで行う処理を定義する
jobs:
  # 処理の名前を定義
  build_:
    # 実行環境や諸々の設定を定義
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    # 実際に行う処理のステップを記載
    steps:
      - name: step1
        run: echo "step1"

      # リポジトリを取り込む？
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          # volta.nodeを参照
          node-version-file: package.json
      - name: npm instal
        run: npm ci

      # ビルドの実行
      - name: next build
        run: npm run build
